Minor UI Changes
amey-balekundri/BE-Project pull request #2
Opened 2021-05-05 11:02 UTC by hbafna1

Home Page UI Changes, 1 Image added.

2021-05-05 14:40 UTC, amey-balekundri requested changes

2021-05-05 14:40 UTC, amey-balekundri commented on web/doctor/templates/doctor/patient_reports.html
> +    <a onclick="myFunction()" href="https://ipfs.infura.io/ipfs/{{i.2}}" class="btn btn-info mx-auto" target="_blank">View Report</a>
remove onclick function

2021-05-05 14:40 UTC, amey-balekundri commented on web/doctor/templates/doctor/patient_reports.html
> +<script>
remove this function

2021-05-06 05:47 UTC, hbafna1 reviewed
Changes Done.

2021-05-07 05:10 UTC, merged

2021-05-07 05:11 UTC, amey-balekundri commented
Merged